### ISSUE TITLE
Crtl-z does not reset the Pathfinder to correct state

### ISSUE THREAD

**Issue by jord1e** [jonathanawesome/graphiql-prototype#63]
This also causes it to reset the manually typed query when pressing a pathfinder item again
![abcd](https://user-images.githubusercontent.com/30464310/181026689-ea67f3bc-f7cc-494f-8826-4b90a2a5ee0f.gif)

**Comment by jonathanawesome** [comment]
fixed with new pathfinder + monaco integration
